[package]
name = "example-cli-rs"
version = "0.1.0"
authors = ["Toby Smith <toby@tismith.id.au>"]
license = "MIT"

[dependencies]
failure = "0.1.1"
log = "0.4.2"
stderrlog = "0.3.0"
clap = "2.32.0"
exitfailure = "0.4.1"

[dev-dependencies]
assert_cli = "0.6"
